### ISSUE TITLE
Some problem with the file paths/name with ver5.1

### ISSUE THREAD

**Issue by Emil-A-02** [HugoTini/DeepBump#16] opened 2023-03-10 22:21 UTC
I could not enable the add on since it seemed to be looking for version 5.0... I installed version 5.0 and it worked fine. Is this an easy fix?

**Comment by HugoTini** [comment] 2023-03-14 01:16
This might have been caused by the naming of the version (having the addon ending with two `.`  as in  `5.1.zip` seems to be confusing blender). Should be fixed now in v6 (feel free to re-open an issue if it still does not work for you)

**Closed as completed** 2023-03-14 01:16 UTC
